Repository SUSE/skuba, pull requests merged in 2019-12, with the labels that each got.

#853 Refactor bsc#1155810
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/kubernetes/kubelet.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: enhancement

#871 Enhance skuba auth login help message
  cmd/skuba/auth/login.go
  docs/man/skuba-auth-login.1.md
  scripts/go-vet.sh
Labels: bug

#886 Fix unable to bootstrap by using FQDN
  internal/pkg/skuba/deployments/ssh/kubelet.go
Labels: bug

#888 kured: remove extra quotes from annotation
  internal/pkg/skuba/kured/kured.go
Labels: 4.1.0, bug

#876 Check preconditions on worker nodes before upgrading
  internal/pkg/skuba/upgrade/node/versions.go
  pkg/skuba/actions/node/upgrade/apply.go
  pkg/skuba/actions/node/upgrade/plan.go
Labels: 4.1.0, bug

#890 Check preconditions on worker nodes before upgrading
  internal/pkg/skuba/upgrade/node/versions.go
  pkg/skuba/actions/node/upgrade/apply.go
  pkg/skuba/actions/node/upgrade/plan.go
Labels: 4.1.0, bug

#891 cluster upgrade plan: remove misleading message
  pkg/skuba/actions/cluster/upgrade/plan.go
Labels: 4.1.0, bug

#882 Enhance addon unit test
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/skuba/configmap.go
  internal/pkg/skuba/upgrade/addon/versions_test.go
Labels: enhancement

#905 Do not panic when version Unknown (bsc#1159452)
  internal/pkg/skuba/kubernetes/node_version.go
  internal/pkg/skuba/kubernetes/node_version_test.go
Labels: bug

#860 Dex and Gangway replica off-balanced (bsc#1157337)
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/replica/replica.go
  internal/pkg/skuba/replica/replica_test.go
  internal/pkg/skuba/replica/testing.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/remove/remove.go
Labels: bug
