Repository SUSE/skuba, pull requests merged in 2019-11, with the labels that each got.

#666 Add worker and master removal tests
  ci/Makefile
  ci/infra/testrunner/tests/test_masters.py
  ci/infra/testrunner/tests/test_workers.py
  ci/jenkins/jobs.yaml
  ci/jenkins/templates/e2e-nightly-template.yaml
Labels: ci

#810 Fix `skuba cluster images` returns wrong values (bsc#1155324)
  cmd/skuba/cluster/images.go
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/kured.go
  internal/pkg/skuba/addons/psp.go
  internal/pkg/skuba/etcd/member.go
  internal/pkg/skuba/kubernetes/kubelet.go
  internal/pkg/skuba/kubernetes/node_version.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/kubernetes/versions_test.go
  internal/pkg/skuba/node/node.go
  internal/pkg/skuba/upgrade/addon/versions.go
  internal/pkg/skuba/upgrade/addon/versions_test.go
  internal/pkg/skuba/upgrade/node/versions_test.go
  pkg/skuba/actions/cluster/images/images.go
  pkg/skuba/actions/cluster/init/init.go
  pkg/skuba/actions/node/join/join.go
Labels: bug

#832 Kubelet use cluster-wide root CA, not per-node (bsc#1155810)
  cmd/skuba/node/bootstrap.go
  cmd/skuba/node/join.go
  cmd/skuba/node/upgrade.go
  internal/pkg/skuba/deployments/deployments.go
  internal/pkg/skuba/deployments/ssh/kubeadm.go
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/deployments/ssh/ssh.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/upgrade/apply.go
  pkg/skuba/constants.go
Labels: bug, documentation

#857 Enhance skuba auth login error message (bsc#1157802)
  cmd/skuba/auth/login.go
  pkg/skuba/actions/auth/auth.go
  pkg/skuba/actions/auth/login.go
  pkg/skuba/actions/auth/login_test.go
Labels: bug, enhancement
