Repository SUSE/skuba, pull requests merged in 2019-07, with the labels that each got.

#526 Fix skuba node join crash if current path admin.conf not exist
  pkg/skuba/actions/node/join/join.go
Labels: bug

#528 Unit test coverage on package bootstrap and join
  internal/pkg/skuba/dex/dex_test.go
  internal/pkg/skuba/dex/testdata/ca.crt
  internal/pkg/skuba/dex/testdata/ca.key
  internal/pkg/skuba/dex/testdata/kubeadm-init.conf
  internal/pkg/skuba/gangway/gangway_test.go
  internal/pkg/skuba/gangway/testdata/ca.crt
  internal/pkg/skuba/gangway/testdata/ca.key
  internal/pkg/skuba/gangway/testdata/kubeadm-init.conf
  pkg/skuba/actions/node/bootstrap/config_test.go
  pkg/skuba/actions/node/bootstrap/testdata/cluster.conf
  pkg/skuba/actions/node/bootstrap/testdata/init.conf
  pkg/skuba/actions/node/bootstrap/testdata/invalid.conf
  pkg/skuba/actions/node/bootstrap/testdata/join.conf
  pkg/skuba/actions/node/join/config_test.go
  pkg/skuba/actions/node/join/testdata/invalid.conf
  pkg/skuba/actions/node/join/testdata/join.conf
Labels: enhancement, test

#501 e2e tests for skuba upgrade plan
  ci/Makefile
  ci/infra/testrunner/README.md
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/testrunner.py
  ci/infra/testrunner/tests/test_skuba_upgrade.py
  ci/jenkins/jobs.yaml
  ci/jenkins/pipelines/skuba-upgrade-nightly.Jenkinsfile
  ci/jenkins/templates/upgrade-nightly-template.yaml
Labels: ci
