Repository SUSE/skuba, pull requests merged in 2019-08, with the labels that each got.

#537 Change dex/gangway title as ClusterName
  pkg/skuba/actions/cluster/init/manifests.go
Labels: enhancement

#529 Add --strict-cap-defaults
  internal/app/skuba/cluster/init.go
  internal/pkg/skuba/deployments/deployments.go
  internal/pkg/skuba/deployments/ssh/cri.go
  pkg/skuba/actions/cluster/init/constants.go
  pkg/skuba/actions/cluster/init/init.go
  pkg/skuba/actions/cluster/init/manifests.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/reset/reset.go
  pkg/skuba/constants.go
Labels: bug, documentation, enhancement, test

#566 Add skuba auth login man pages
  docs/man/skuba-auth-login.1.md
  docs/man/skuba.1.md
  internal/app/skuba/auth/login.go
Labels: documentation

#564 Add testcase for bsc#1142552
  ci/infra/testrunner/tests/test_dockercaps.py
Labels: test

#606 [WIP] put ssh agent sock in $TMP and verify length
  ci/infra/testrunner/platforms/platform.py
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/utils/utils.py
Labels: ci

#611 Remove the build skuba command from testrunner
  ci/Makefile
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/testrunner.py
  ci/infra/testrunner/utils/utils.py
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/skuba-nightly.Jenkinsfile
Labels: ci

#613 Fix ssh-agent cleanup.
  ci/infra/testrunner/utils/utils.py
Labels: ci

#571 Add verbosity to CI skuba execution
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/utils/constants.py
  ci/infra/testrunner/vars.yaml
Labels: ci

#620 Wait for nodes to be ready before upgrade
  ci/infra/testrunner/tests/test_skuba_upgrade.py
Labels: ci

#625 Add skuba binary path to conformance test pipe
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
Labels: ci

#626 Make sure to remove the built skuba
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
  ci/jenkins/pipelines/skuba-e2e-nightly.Jenkinsfile
  ci/jenkins/pipelines/skuba-nightly.Jenkinsfile
Labels: ci

#628 Collect node logs after e2e tests
  ci/infra/testrunner/tests/README.md
  ci/infra/testrunner/tests/conftest.py
  ci/infra/testrunner/tests/test_skuba_upgrade.py
  ci/infra/testrunner/tests/test_workers.py
Labels: ci

#572 Add skuba auth login unit test
  internal/app/skuba/auth/login.go
  pkg/skuba/actions/auth/auth.go
  pkg/skuba/actions/auth/login.go
  pkg/skuba/actions/auth/login_test.go
  pkg/skuba/actions/auth/testdata/invalid.crt
  pkg/skuba/actions/auth/testdata/localhost.crt
  pkg/skuba/actions/auth/testdata/localhost.key
  pkg/skuba/actions/auth/testing.go
  pkg/skuba/actions/cluster/init/init.go
Labels: test

#616 Make sure nodes are ready and upgraded
  ci/infra/testrunner/tests/test_skuba_upgrade.py
Labels: ci

#624 Enable nightly e2e tests
  ci/Makefile
  ci/jenkins/jobs.yaml
  ci/jenkins/templates/e2e-nightly-template.yaml
Labels: ci

#631 Don't use bootstrap fixture on upgrades
  ci/infra/testrunner/tests/test_skuba_upgrade.py
Labels: ci

#635 Multinode upgrade
  ci/infra/testrunner/tests/test_skuba_upgrade.py
Labels: ci

#633 Added ability to skip deployment steps
  ci/infra/testrunner/testrunner.py
  ci/infra/testrunner/tests/conftest.py
  ci/infra/testrunner/tests/driver.py
Labels: ci

#636 Enable e2e tests on vmware
  ci/jenkins/jobs.yaml
Labels: ci

#614 Run testrunner scenarios instead of ginko
  ci/Makefile
  ci/infra/testrunner/testrunner.py
  ci/infra/testrunner/tests/conftest.py
  ci/infra/testrunner/tests/driver.py
  ci/infra/testrunner/tests/pytest.ini
  ci/infra/testrunner/tests/test_cilium.py
  ci/infra/testrunner/tests/test_dockercaps.py
  ci/infra/testrunner/tests/test_skuba_upgrade.py
  ci/infra/testrunner/tests/test_workers.py
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/skuba-nightly.Jenkinsfile
Labels: ci

#629 Skuba auth login supports multiple connectors (bsc#1145878)
  docs/man/skuba-auth-login.1.md
  internal/app/skuba/auth/login.go
  pkg/skuba/actions/auth/auth.go
  pkg/skuba/actions/auth/auth_test.go
  pkg/skuba/actions/auth/login.go
  pkg/skuba/actions/auth/login_test.go
  pkg/skuba/actions/auth/testing.go
Labels: bug

#648 Fix PR got merged, CI test failed
  ci/jenkins/pipelines/prs/helpers/pr_manager/pr_manager.py
Labels: ci

#634 Added reboot node tests
  ci/infra/testrunner/tests/driver.py
  ci/infra/testrunner/tests/test_node_reboot.py
Labels: ci

#671 Increased wait time for pods to be ready
  ci/infra/testrunner/tests/test_node_reboot.py
Labels: ci

#669 Increase unit-test code coverage for node remove
  internal/pkg/skuba/etcd/member.go
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubernetes/jobs.go
  internal/pkg/skuba/kubernetes/kubelet.go
  internal/pkg/skuba/upgrade/cluster/drift.go
  internal/pkg/skuba/upgrade/cluster/versions.go
  internal/pkg/skuba/upgrade/node/versions.go
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/remove/remove.go
  pkg/skuba/actions/node/remove/remove_test.go
  pkg/skuba/actions/node/upgrade/apply.go
  pkg/skuba/actions/node/upgrade/plan.go
Labels: test
