Repository SUSE/skuba, pull requests merged in 2019-10, with the labels that each got.

#743 Handle unstable builds
  ci/jenkins/pipelines/prs/skuba-code-lint.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-jjb-validation.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-test-vmware.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-update-acceptance.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-update-unit.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-validate-pr-author.Jenkinsfile
Labels: ci

#750 Remove external Javascript and CSS resource (bsc#1148412)
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/kubernetes/versions.go
Labels: bug

#742 Add e2e test for skuba addon upgrades
  ci/Makefile
  ci/infra/testrunner/kubectl/kubectl.py
  ci/infra/testrunner/requirements.txt
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/tests/test_skuba_addon_upgrade.py
  ci/infra/testrunner/utils/utils.py
  ci/jenkins/jobs.yaml
  ci/jenkins/templates/e2e-nightly-template.yaml
Labels: ci, test

#772 Enhance e2e tests for addon upgrade
  ci/infra/testrunner/tests/test_skuba_addon_upgrade.py
Labels: ci

#793 skuba node upgrade shows component downgrade (bsc#1154085)
  .github/pull_request_template.md
  internal/pkg/skuba/etcd/member_test.go
  internal/pkg/skuba/upgrade/node/versions.go
  internal/pkg/skuba/upgrade/node/versions_test.go
Labels: bug

#798 Reboot can be triggered before skuba-update finish (bsc#1153928)
  skuba-update/skuba_update/skuba_update.py
  skuba-update/test/unit/skuba_update_test.py
Labels: bug

#799 Output available addon updates by name
  internal/pkg/skuba/upgrade/addon/versions.go
Labels: ci

#795 Fix node upgrade not success if patch version bump (bsc#1155173)
  internal/pkg/skuba/kubernetes/node_version.go
  internal/pkg/skuba/kubernetes/node_version_test.go
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  internal/pkg/skuba/upgrade/cluster/drift.go
  internal/pkg/skuba/upgrade/node/versions.go
  internal/pkg/skuba/upgrade/node/versions_test.go
  pkg/skuba/actions/addon/upgrade/apply.go
  pkg/skuba/actions/addon/upgrade/plan.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: bug
