Repository SUSE/skuba, pull requests merged in 2020-12, with the labels that each got.

#1453 Updates message to a consistent language
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/cluster/upgrade/plan_test.go
Labels: backport, cosmetic

#1454 Updates message to a consistent language
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/cluster/upgrade/plan_test.go
Labels: cosmetic

#1462 Fix kubectl server-side dry-run flag
  internal/pkg/skuba/addons/addons.go
Labels: bug

#1459 addons: cilium: Add missing ClusterRoles rules (bsc#1178931)
  internal/pkg/skuba/addons/cilium_manifests/v17.go
Labels: do not merge

#1463 Fix kubectl server-side dry-run flag (backport to v4.5)
  internal/pkg/skuba/addons/addons.go
Labels: backport, bug
