Repository SUSE/skuba, pull requests merged in 2020-02, with the labels that each got.

#944 Add hard reboot test to e2e
  ci/Makefile
  ci/jenkins/jobs.yaml
Labels: ci

#908 Pass verbose level to kubeadm
  cmd/skuba/flags/verbose.go
  cmd/skuba/main.go
  cmd/skuba/node/bootstrap.go
  cmd/skuba/node/join.go
  cmd/skuba/node/upgrade.go
  internal/pkg/skuba/deployments/ssh/kubeadm.go
  internal/pkg/skuba/deployments/ssh/ssh.go
Labels: enhancement

#955 Fix skuba-update --version always 0.0.0 (bsc#1160463)
  ci/packaging/suse/skuba_spec_template
Labels: bug

#924 Isolate libvirt deployment disk size by role
  ci/infra/libvirt/lb-instances.tf
  ci/infra/libvirt/master-instance.tf
  ci/infra/libvirt/variables.tf
  ci/infra/libvirt/worker-instance.tf
Labels: enhancement

#949 [CI Update packages in worker before deploying
  ci/Makefile
Labels: ci

#960 Disable firewall in vmware+libvirt load balancers (SUSE/avant-garde#1337)
  ci/infra/libvirt/cloud-init/lb.tpl
  ci/infra/vmware/cloud-init/lb.tpl
Labels: bug

#957 Add some IBS automation
  ci/packaging/suse/rpmfiles_maker.sh
Labels: ci, enhancement

#956 [ci] Fix vmware job (SUSE/avant-garde#1299)
  ci/jenkins/pipelines/prs/skuba-test-vmware.Jenkinsfile
Labels: bug, ci

#958 fix exception logging in testrunner
  ci/infra/testrunner/testrunner.py
Labels: bug

#950 CI: Use NUE VMware cluster in CI
  ci/infra/vmware/terraform.tfvars.json.ci.example
Labels: CI

#965 Better node count for tests
  ci/infra/testrunner/kubectl/kubectl.py
  ci/infra/testrunner/tests/test_masters.py
Labels: CI, test

#970 Remove firewalld actions on libvirt
  ci/infra/libvirt/cloud-init/lb.tpl
Labels: bug

#975 CI: Make jenkins/skuba-test run on VMWare cluster
  ci/jenkins/pipelines/prs/skuba-test-vmware.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: CI
