Repository SUSE/skuba, pull requests merged in 2020-11, with the labels that each got.

#1415 Create temp dir to stores kubeadm-init.conf to fix CVE-2020-8030 (bsc#1177361)
  internal/pkg/skuba/deployments/ssh/kubeadm.go
Labels: security

#1424 Create temp dir to stores kubeadm-init.conf to fix CVE-2020-8030 (bsc#1177361) (backport to v4.2)
  internal/pkg/skuba/deployments/ssh/kubeadm.go
Labels: backport, security

#1416 Add file permission for upload file method to fix CVE-2020-8029 (bsc#1177362)
  internal/pkg/skuba/deployments/deployments.go
  internal/pkg/skuba/deployments/ssh/cri.go
  internal/pkg/skuba/deployments/ssh/files.go
  internal/pkg/skuba/deployments/ssh/kernel.go
  internal/pkg/skuba/deployments/ssh/kubeadm.go
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/deployments/ssh/oidc.go
Labels: security

#1428 Add file permission for upload file method to fix CVE-2020-8029 (bsc#1177362) (backport to v4.2)
  internal/pkg/skuba/deployments/deployments.go
  internal/pkg/skuba/deployments/ssh/cri.go
  internal/pkg/skuba/deployments/ssh/files.go
  internal/pkg/skuba/deployments/ssh/kernel.go
  internal/pkg/skuba/deployments/ssh/kubeadm.go
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/deployments/ssh/kubernetes.go
Labels: backport, security

#1434 Re-render all addons base manifest during bootstrap (#1312) (backport to v4.2)
  internal/pkg/skuba/addons/metricsserver.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
Labels: 4.2.4, backport, bug

#1433 Rename kubernetes client package
  internal/pkg/skuba/deployments/ssh/kubernetes.go
Labels: 4.5.2, ci-repo:k8sclt_split

#1435 CI tests can't distinguish patch level versions of k8s
  ci/infra/testrunner/tests/utils.py
Labels: CI

#1438 Bump cri-o up to 1.18.4 (bsc#1178785)
  internal/pkg/skuba/kubernetes/versions.go
Labels: ci-repo:cri-o_update

#1439 Inhibit kured on CI cluster upgrade
  ci/jenkins/pipelines/skuba-upgrade-from-4.2.Jenkinsfile
Labels: CI, bug

#1450 Fixes issues in validation script
  ci/jenkins/pipelines/prs/helpers/pr_manager/pr_checks.py
Labels: bug
