Repository SUSE/skuba, pull requests merged in 2020-04, with the labels that each got.

#1020 Terraform libvirt lb fixes
  ci/infra/libvirt/cloud-init/common.tpl
  ci/infra/libvirt/cloud-init/lb.tpl
  ci/infra/libvirt/cloud-init/register-rmt.tpl
  ci/infra/libvirt/cloud-init/register-scc.tpl
  ci/infra/libvirt/lb-instances.tf
  ci/infra/libvirt/master-instance.tf
  ci/infra/libvirt/output.tf
  ci/infra/libvirt/registration.auto.tfvars
  ci/infra/libvirt/terraform.tfvars.example
  ci/infra/libvirt/variables.tf
  ci/infra/libvirt/worker-instance.tf
Labels: CI, bug

#1043 Fix PSP for kubelet disarm job, bsc#1138908
  internal/pkg/skuba/addons/psp.go
  internal/pkg/skuba/kubernetes/kubelet.go
  internal/pkg/skuba/kubernetes/versions.go
Labels: 4.2.0, security

#1057 Remove openstack e2e tests from CI
  ci/jenkins/jobs.yaml
Labels: CI

#1062 1.17 skuba is now deployed with crio 1.16.1
  internal/pkg/skuba/kubernetes/versions.go
Labels: 4.2.0, bug

#1063 Missing cloud-config file should fail bootstrap
  internal/pkg/skuba/deployments/ssh/kubelet.go
Labels: enhancement

#1012 addons: Cilium 1.6.6 and Envoy
  go.mod
  go.sum
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/cilium_test.go
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/kured.go
  internal/pkg/skuba/addons/metricsserver.go
  internal/pkg/skuba/addons/psp.go
  internal/pkg/skuba/cni/cilium.go
  internal/pkg/skuba/cni/cilium_test.go
  internal/pkg/skuba/cni/errors.go
  internal/pkg/skuba/kubernetes/clientset.go
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/versions.go
  pkg/skuba/actions/cluster/status/status.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/remove/remove.go
  pkg/skuba/actions/node/remove/remove_test.go
Labels: 4.2.1, enhancement, high-priority
