Repository SUSE/skuba, pull requests merged in 2020-06, with the labels that each got.

#1134 Use Repository branch from ci-repo label
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-repo:Test_Branch_Repos

#997 Require go version 1.13
  Makefile
  ci/packaging/suse/skuba_spec_template
  go.mod
Labels: ci-label:go13, ci-worker:experimental, v5

#1107 Upgrade k8s libraries
  go.mod
  go.sum
  internal/pkg/skuba/cni/cilium.go
  internal/pkg/skuba/cni/cilium_test.go
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/dex/dex.go
  internal/pkg/skuba/etcd/member_test.go
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubernetes/jobs.go
  internal/pkg/skuba/kubernetes/jobs_test.go
  internal/pkg/skuba/kubernetes/kubelet.go
  internal/pkg/skuba/kubernetes/node_version.go
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/pod.go
  internal/pkg/skuba/kubernetes/resources_test.go
  internal/pkg/skuba/kured/kured.go
  internal/pkg/skuba/metricsserver/metricsserver.go
  internal/pkg/skuba/node/common.go
  internal/pkg/skuba/node/config.go
  internal/pkg/skuba/node/config_test.go
  internal/pkg/skuba/replica/replica.go
  internal/pkg/skuba/replica/replica_test.go
  internal/pkg/skuba/skuba/configmap.go
  internal/pkg/skuba/upgrade/node/versions.go
  internal/pkg/skuba/util/cert.go
  internal/pkg/skuba/util/cert_test.go
  pkg/skuba/actions/cluster/status/status.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/remove/remove.go
  pkg/skuba/actions/node/remove/remove_test.go
Labels: ci-label:go13, ci-worker:experimental, v5

#1132 Adapt terraform tfvars to start using SLE_15_SP2 repositories and CaaSP v5 devel projects
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/openstack/terraform.tfvars.json.ci.example
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-worker:experimental-v5, v5

#1138 AutoYaST adapted for CaaSP 5 based on SLE-15-SP2
  ci/infra/bare-metal/autoyast.xml
Labels: v5

#1141 Switch daily job version branches
  ci/jenkins/jobs.yaml
Labels: do not merge, v5

#1140 Switch to v5 CR container images
  pkg/skuba/development_constants.go
Labels: ci-label:go13, ci-worker:experimental-v5, v5

#1177 Fix the branched repo url
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: CI

#1093 Get disk format from template on VMware, fixes bsc#1171349
  ci/infra/vmware/lb-instance.tf
  ci/infra/vmware/master-instance.tf
  ci/infra/vmware/variables.tf
  ci/infra/vmware/worker-instance.tf
Labels: documentation, release, v5

#1173 Do not render empty client secret (bsc#1173055)
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/gangway_test.go
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/gangway/gangway_test.go
Labels: 4.2.1, bug

#1181 [terraform] fix mtu from 1400 to standard 1500
  ci/infra/aws/cloud-init/cloud-init.yaml.tpl
  ci/infra/libvirt/cloud-init/common.tpl
  ci/infra/openstack/cloud-init/common.tpl
Labels: enhancement

#1174 Single source of oidc client secret (bsc#1173055)
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/cilium_test.go
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/dex_test.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/gangway_test.go
  internal/pkg/skuba/addons/generic.go
  internal/pkg/skuba/addons/kucero.go
  internal/pkg/skuba/addons/metricsserver.go
  internal/pkg/skuba/cni/cilium_test.go
  internal/pkg/skuba/dex/dex.go
  internal/pkg/skuba/dex/dex_test.go
  internal/pkg/skuba/dex/testdata/kubeadm-init.conf
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/gangway/gangway_test.go
  internal/pkg/skuba/gangway/testdata/ca.crt
  internal/pkg/skuba/gangway/testdata/ca.key
  internal/pkg/skuba/gangway/testdata/kubeadm-init.conf
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/oidc/cert.go
  internal/pkg/skuba/oidc/cert_test.go
  internal/pkg/skuba/oidc/oidc.go
  internal/pkg/skuba/oidc/resource.go
  internal/pkg/skuba/oidc/resource_test.go
  internal/pkg/skuba/oidc/testdata/ca.crt
  internal/pkg/skuba/oidc/testdata/ca.key
  internal/pkg/skuba/oidc/util.go
  internal/pkg/skuba/oidc/util_test.go
  internal/pkg/skuba/util/controlplane.go
  internal/pkg/skuba/util/controlplane_test.go
  pkg/skuba/actions/cluster/init/init.go
Labels: bug, enhancement, v5

#1183 Set image alternate mirror from ci-repo label
  ci/Makefile
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: wip

#1190 Use env var for AWS credentials
  ci/infra/aws/README.md
  ci/infra/aws/ami.tf
  ci/infra/aws/aws.tf
  ci/infra/aws/network.tf
  ci/infra/aws/terraform.tfvars.example
  ci/infra/aws/variables.tf
Labels: documentation, enhancement

#1191 Update cri-o runtime to version 1.18.2
  internal/pkg/skuba/kubernetes/versions.go
Labels: 5.0.0

#1204 Bump kubernetes libraries to 1.18.5
  ci/infra/testrunner/tests/utils.py
  go.mod
  go.sum
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/kubernetes/versions_test.go
Labels: ci-repo:bump-k8s

#1155 Add Cilium 1.7 manifests
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/cilium_manifests/v15.go
  internal/pkg/skuba/addons/cilium_manifests/v16.go
  internal/pkg/skuba/addons/cilium_manifests/v17.go
  internal/pkg/skuba/cni/cilium.go
  internal/pkg/skuba/kubernetes/versions.go
Labels: ci-repo:cilium17, v5

#1178 Support Patternless kubernetes and crio packages
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/deployments/ssh/zypper.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: ci-repo:pattern-less
