Repository SUSE/skuba, pull requests merged in 2020-10, with the labels that each got.

#1391 Add label to set specific kubernetes version in PR
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-kubernetes:1.18.6

#1371 Enable automatic release build via GitHub Actions
  .github/workflows/create_release.yaml
  ci/packaging/suse/changelog_maker.sh
  ci/packaging/suse/rpmfiles_maker.sh
Labels: release

#1400 Upgrade of k8s (CVE-2020-8564, CVE-2020-8565, bsc#1177660, bsc#1177661)
  ci/infra/testrunner/tests/utils.py
  internal/pkg/skuba/kubeadm/configmap_test.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/kubernetes/versions_test.go
Labels: ci-repo:k8s_upgrade

#1398 Set up automatic release generation on v* tag
  .github/workflows/create_release.yaml
  ci/packaging/suse/changelog_maker.sh
  ci/packaging/suse/rpmfiles_maker.sh
Labels: backport, ci-worker:maintenance-caasp-v4.2

#1406 feat: refresh local addon base manifests (backport to v4.2)
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/tests/test_addon_upgrade.py
  cmd/skuba/addon.go
  cmd/skuba/addon/refresh.go
  docs/man/skuba-addon-refresh-localconfig.1.md
  docs/man/skuba.1.md
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/addons_test.go
  pkg/skuba/actions/addon/refresh/localconfig.go
  pkg/skuba/actions/addon/upgrade/apply.go
  pkg/skuba/actions/addon/upgrade/plan.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: 4.2.4, backport

#1407 fix: check the addon belongs to current cluster version
  internal/pkg/skuba/addons/addons.go
  pkg/skuba/actions/addon/refresh/localconfig.go
Labels: bug

#1409 Fix nodeVersion for all upgrade plan
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/cluster/upgrade/plan_test.go
Labels: 4.2.4, backport
