Repository SUSE/skuba, pull requests merged in 2020-05, with the labels that each got.

#1072 vsphere: support set hostname from dhcp server
  ci/infra/vmware/cloud-init/common.tpl
  ci/infra/vmware/cloud-init/lb.tpl
  ci/infra/vmware/lb-instance.tf
  ci/infra/vmware/main.tf
  ci/infra/vmware/master-instance.tf
  ci/infra/vmware/terraform.tfvars.example
  ci/infra/vmware/variables.tf
  ci/infra/vmware/worker-instance.tf
Labels: enhancement

#1098 Enhance terraform vsphere_resource_pool example
  ci/infra/vmware/terraform.tfvars.example
Labels: enhancement

#1084 libvirt/openstack: support set hostname from dhcp server
  ci/infra/libvirt/cloud-init/common.tpl
  ci/infra/libvirt/lb-instances.tf
  ci/infra/libvirt/master-instance.tf
  ci/infra/libvirt/terraform.tfvars.example
  ci/infra/libvirt/variables.tf
  ci/infra/libvirt/worker-instance.tf
  ci/infra/openstack/cloud-init/common.tpl
  ci/infra/openstack/master-instance.tf
  ci/infra/openstack/terraform.tfvars.example
  ci/infra/openstack/variables.tf
  ci/infra/openstack/worker-instance.tf
Labels: enhancement

#1105 Set suitable values for maxUnavailable in addons
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/kured.go
  internal/pkg/skuba/kubernetes/versions.go
Labels: enhancement

#1116 Set CI labels from PR labels
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-label:test, ci-platform:libvirt

#1120 CI: Reorganize jobs per caasp version
  ci/jenkins/jobs.yaml
  ci/jenkins/templates/conformance-template.yaml
  ci/jenkins/templates/e2e-daily-template.yaml
  ci/jenkins/templates/e2e-update-daily-template.yaml
Labels: do not merge

#1117 Set platform from pr label
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-label:kvm, ci-platform:libvirt

#1125 Use experimental workers in PR
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-worker:experimental, do not merge

#1126 Refactor all pr validation code into the pr-test pipeline
  ci/jenkins/jobs.yaml
  ci/jenkins/pipelines/prs/skuba-code-lint.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-validate-pr-author.Jenkinsfile
  ci/jenkins/templates/code-author.yaml
  ci/jenkins/templates/code-lint.yaml
Labels: do not merge
