Repository SUSE/skuba, pull requests merged in 2020-08, with the labels that each got.

#1282 Enable ExtendedResourceToleration by default (#1192)
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubeadm/configmap_test.go
Labels: 5.0.0

#1243 Avoid pulling plugins from the Terraform online repositry
  ci/infra/testrunner/platforms/terraform.py
Labels: backport

#1277 Drain nodes before kubadm upgrade and uncordon afterwards
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: backport

#1296 fix gangway revision (bsc#1173165)
  internal/pkg/skuba/kubernetes/versions.go
Labels: backport

#1294 updated version to v4.5
  README.md
  ci/infra/aws/cloud-init/register-rmt.tpl
  ci/infra/aws/cloud-init/register-scc.tpl
  ci/infra/azure/cloud-init/register-rmt.tpl
  ci/infra/azure/cloud-init/register-scc.tpl
  ci/infra/bare-metal/autoyast.xml
  ci/infra/libvirt/cloud-init/register-rmt.tpl
  ci/infra/libvirt/cloud-init/register-scc.tpl
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/openstack/cloud-init/register-rmt.tpl
  ci/infra/openstack/cloud-init/register-scc.tpl
  ci/infra/openstack/terraform.tfvars.json.ci.example
  ci/infra/testrunner/tests/test_istio_deployment.py
  ci/infra/vmware/README.md
  ci/infra/vmware/cloud-init/register-rmt.tpl
  ci/infra/vmware/cloud-init/register-scc.tpl
  ci/infra/vmware/terraform.tfvars.example
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/jenkins/jobs.yaml
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/skuba-e2e-test.Jenkinsfile
  ci/packaging/suse/skuba_spec_template
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/kubernetes/node_version_test.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  internal/pkg/skuba/kubernetes/pod_test.go
  pkg/skuba/development_constants.go
  pkg/skuba/release_constants.go
  pkg/skuba/staging_constants.go
Labels: backport, do not merge

#1262 Replace OIDC server certificates signed by custom/trusted certificate authority
  cmd/skuba/cert.go
  cmd/skuba/cert/oidc.go
  cmd/skuba/main.go
  docs/man/skuba-cert-generate-csr.1.md
  docs/man/skuba.1.md
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/deployments/ssh/oidc.go
  internal/pkg/skuba/oidc/cert.go
  internal/pkg/skuba/oidc/cert_test.go
  internal/pkg/skuba/oidc/testdata/ca.crt
  internal/pkg/skuba/oidc/testdata/ca.key
  internal/pkg/skuba/util/cert.go
  internal/pkg/skuba/util/cert_test.go
  pkg/skuba/actions/cert/oidc.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
Labels: v5

#1312 Re-render all addons base manifest during bootstrap
  internal/pkg/skuba/addons/metricsserver.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
Labels: bug

#1303 Update to cilium 1.7.6 (bsc#1173559)
  internal/pkg/skuba/addons/cilium_test.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/upgrade/addon/versions_test.go
  internal/pkg/skuba/upgrade/node/versions_test.go
Labels: ci-repo:cilium

#1329 Fix kucero PSP (bsc#1175352)
  internal/pkg/skuba/addons/kucero.go
  internal/pkg/skuba/kubernetes/versions.go
Labels: 4.5.0, bug

#1332 Fix list of default admission controllers to upstream defaults
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubeadm/configmap_test.go
Labels: 4.5.0

#1338 Fix incorrect CP container image names from 'skuba cluster images'
  internal/pkg/skuba/kubernetes/versions.go
Labels: 4.5.0, backport
