Repository SUSE/skuba, pull requests merged in 2020-03, with the labels that each got.

#980 Reuse gangway client secret if present
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/gangway/gangway_test.go
  vendor/modules.txt
Labels: bug

#951 Dex and Gangway replica off-balanced (bsc#1157337)
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/kubernetes/nodes.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/replica/replica.go
  internal/pkg/skuba/replica/replica_test.go
  internal/pkg/skuba/replica/testing.go
  pkg/skuba/actions/addon/upgrade/apply.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/remove/remove.go
Labels: bug

#883 Add option to configure datastore_cluster
  ci/infra/vmware/README.md
  ci/infra/vmware/lb-instance.tf
  ci/infra/vmware/master-instance.tf
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/infra/vmware/variables.tf
  ci/infra/vmware/worker-instance.tf
Labels: CI

#984 CI: Use generic vmware resources
  ci/infra/vmware/terraform.tfvars.json.ci.example
Labels: CI

#963 Simplify PR test pipeline (SUSE/avant-garde#1090)
  .gitignore
  ci/Makefile
  ci/infra/testrunner/tests/pytest.ini
  ci/infra/testrunner/tests/test_deployments.py
  ci/infra/testrunner/tests/test_node_reboot.py
  ci/infra/testrunner/tests/test_skuba_addon_upgrade.py
  ci/infra/testrunner/tests/test_workers.py
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: CI

#987 CI: VMWare make sure the var is null
  ci/infra/vmware/variables.tf
Labels: CI, bug

#990 CI: Rename nightly jobs to daily
  ci/jenkins/jobs.yaml
  ci/jenkins/pipelines/skuba-e2e-daily.Jenkinsfile
  ci/jenkins/pipelines/skuba-update-daily.Jenkinsfile
  ci/jenkins/templates/e2e-daily-template.yaml
  ci/jenkins/templates/e2e-update-daily-template.yaml
Labels: CI

#992 CI: Extra command in test run
  ci/Makefile
Labels: CI, bug

#966 feat: add metrics-server addon
  internal/pkg/skuba/addons/metricsserver.go
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/metricsserver/metricsserver.go
  vendor/modules.txt
Labels: enhancement

#993 CI: Allow overriding memory/cpu from vars.yml
  ci/infra/testrunner/platforms/terraform.py
Labels: CI, bug

#995 Add replica HA on metric-server
  internal/pkg/skuba/addons/metricsserver.go
Labels: enhancement

#998 CI: Silence pip actions on PR jobs
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: CI

#983 Include libvirt platform as part of the PRs tests
  ci/infra/libvirt/README.md
  ci/infra/libvirt/main.tf
  ci/infra/libvirt/terraform.tfvars.example
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/libvirt/variables.tf
  ci/infra/testrunner/README.md
  ci/infra/testrunner/platforms/libvirt.py
  ci/infra/testrunner/platforms/openstack.py
  ci/infra/testrunner/platforms/terraform.py
  ci/infra/testrunner/platforms/vmware.py
  ci/infra/testrunner/utils/constants.py
  ci/infra/testrunner/vars.yaml
  ci/jenkins/jobs.yaml
  ci/jenkins/pipelines/prs/skuba-test-libvirt.Jenkinsfile
  ci/jenkins/templates/test-libvirt-template.yaml
Labels: CI

#999 Update libvirt URI to use the node52 alias
  ci/jenkins/pipelines/prs/skuba-test-libvirt.Jenkinsfile
Labels: CI

#1000 CI: wait for sonobuoy to finish tests
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
  ci/tasks/sonobuoy_e2e.py
Labels: CI

#1002 CI: Allow to manually trigger sonobuoy branch tests
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
Labels: CI

#1005 CI: sonobuoy fix a merge fix in jenkinsfile
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
Labels: CI, bug

#1009 CI: break when results found in sonobuoy
  ci/tasks/sonobuoy_e2e.py
Labels: CI

#929 Give skuba the responsability to check for kernel modules
  internal/pkg/skuba/deployments/ssh/kernel.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
Labels: bug

#986 Update global client secret
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/dex_test.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/gangway_test.go
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/gangway/gangway_test.go
Labels: 4.2.0

#1015 CI: improve sonobuoy job
  ci/Makefile
  ci/infra/testrunner/README.md
  ci/infra/testrunner/kubectl/kubectl.py
  ci/infra/testrunner/testrunner.py
  ci/jenkins/pipelines/skuba-conformance.Jenkinsfile
  ci/tasks/sonobuoy_e2e.py
Labels: CI, bug
