Repository SUSE/skuba, pull requests merged in 2020-09, with the labels that each got.

#1363 Updated cilium to rev3 to handle cilium-proxy updates
  internal/pkg/skuba/kubernetes/versions.go
Labels: ci-repo:4.5.1

#1362 Update cilium to 1.7.6 and image to rev3
  internal/pkg/skuba/kubernetes/versions.go
Labels: backport, ci-repo:4.5.1, do not merge

#1367 Remove hyperkube migration
  pkg/skuba/actions/node/upgrade/apply.go
Labels: backport, high-priority

#1360 [backport] Backport image mirroring for testing
  ci/infra/testrunner/README.md
  ci/infra/testrunner/platforms/platform.py
  ci/infra/testrunner/requirements.txt
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/testrunner.py
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: backport

#1349 Change branches in e2e manual test
  ci/jenkins/pipelines/skuba-e2e-test.Jenkinsfile
  ci/jenkins/templates/e2e-dev-template.yaml
Labels: CI, wip

#1350 [TF] Handle resource name errors
  ci/infra/openstack/output.tf
Labels: bug

#1370 Informs the user about wrong OS on node
  internal/pkg/skuba/upgrade/node/versions.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: 4.5.0

#1359 [CI] Use shared lib functions for PR job
  ci/jenkins/pipelines/skuba-handle-pr.Jenkinsfile
Labels: CI

#1373 Fix output.tf for openstack
  ci/infra/openstack/output.tf
Labels: bug
