Repository SUSE/skuba, pull requests merged in 2020-07, with the labels that each got.

#1205 Fix the reboot logic
  ci/infra/libvirt/master-instance.tf
  ci/infra/libvirt/terraform.tfvars.example
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/libvirt/worker-instance.tf
  ci/infra/openstack/master-instance.tf
  ci/infra/openstack/terraform.tfvars.example
  ci/infra/openstack/terraform.tfvars.json.ci.example
  ci/infra/openstack/worker-instance.tf
  ci/infra/vmware/terraform.tfvars.example
  ci/infra/vmware/terraform.tfvars.json.ci.example
Labels: 5.0.0

#1188 Single source of oidc client secret (bsc#1173055) backport to v4
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/cilium.go
  internal/pkg/skuba/addons/cilium_test.go
  internal/pkg/skuba/addons/dex.go
  internal/pkg/skuba/addons/dex_test.go
  internal/pkg/skuba/addons/gangway.go
  internal/pkg/skuba/addons/gangway_test.go
  internal/pkg/skuba/addons/generic.go
  internal/pkg/skuba/addons/metricsserver.go
  internal/pkg/skuba/cni/cilium_test.go
  internal/pkg/skuba/dex/dex.go
  internal/pkg/skuba/dex/dex_test.go
  internal/pkg/skuba/dex/testdata/kubeadm-init.conf
  internal/pkg/skuba/gangway/gangway.go
  internal/pkg/skuba/gangway/gangway_test.go
  internal/pkg/skuba/gangway/testdata/ca.crt
  internal/pkg/skuba/gangway/testdata/ca.key
  internal/pkg/skuba/gangway/testdata/kubeadm-init.conf
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/oidc/cert.go
  internal/pkg/skuba/oidc/cert_test.go
  internal/pkg/skuba/oidc/oidc.go
  internal/pkg/skuba/oidc/resource.go
  internal/pkg/skuba/oidc/resource_test.go
  internal/pkg/skuba/oidc/testdata/ca.crt
  internal/pkg/skuba/oidc/testdata/ca.key
  internal/pkg/skuba/oidc/util.go
  internal/pkg/skuba/oidc/util_test.go
  internal/pkg/skuba/util/controlplane.go
  internal/pkg/skuba/util/controlplane_test.go
  pkg/skuba/actions/cluster/init/init.go
Labels: bug

#1207 Switch to SLE15-SP2 base images and change references to v5
  README.md
  ci/infra/aws/ami.tf
  ci/infra/aws/master-instance.tf
  ci/infra/aws/worker-instance.tf
  ci/infra/azure/README.md
  ci/infra/azure/main.tf
  ci/infra/azure/master-instance.tf
  ci/infra/azure/worker-instance.tf
  ci/infra/testrunner/tests/test_dockercaps.py
  ci/infra/vmware/README.md
  ci/infra/vmware/terraform.tfvars.example
  ci/infra/vmware/terraform.tfvars.json.ci.example
  internal/pkg/skuba/kubernetes/node_version_test.go
  internal/pkg/skuba/kubernetes/nodes_test.go
  internal/pkg/skuba/kubernetes/pod_test.go
  skuba-update/test/os/suse/Makefile
Labels: 5.0.0

#1221 Fix packaging script
  ci/packaging/suse/rpmfiles_maker.sh
Labels: CI

#1222 add missing tags and format AWS tf
  ci/infra/aws/aws.tf
  ci/infra/aws/iam_policies.tf
  ci/infra/aws/load-balancer.tf
  ci/infra/aws/network.tf
Labels: bug

#1192 Enable ExtendedResourceToleration by default
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubeadm/configmap_test.go
Labels: 5.0.0, enhancement

#1231 Add Openstack credentials to PR test job
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci-platform:openstack

#1185 Allow ssh through bastion with skuba
  docs/man/skuba-node-bootstrap.1.md
  docs/man/skuba-node-join.1.md
  docs/man/skuba-node-upgrade-apply.1.md
  internal/pkg/skuba/deployments/ssh/ssh.go
Labels: documentation, enhancement

#1233 CI: Bump vmware image to latest
  ci/infra/vmware/terraform.tfvars.json.ci.example
Labels: CI

#1227 Allow any version of k8s-client for skuba-update and allow cri-o bump during stage1
  ci/packaging/suse/skuba_spec_template
  internal/pkg/skuba/deployments/ssh/kubernetes.go
Labels: ci-repo:k8sProvides

#1244 Update kured to 1.4.3
  internal/pkg/skuba/kubernetes/versions.go
Labels: ci-repo:kured-update

#1236 CI: disable routable check for vmware
  ci/infra/vmware/lb-instance.tf
  ci/infra/vmware/master-instance.tf
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/infra/vmware/variables.tf
  ci/infra/vmware/worker-instance.tf
Labels: CI, bug

#1252 Install cri-tools-<cri_version>
  internal/pkg/skuba/deployments/ssh/kubernetes.go
Labels: ci-repo:cri-tools

#1240 [5.0] CI: disable routable check for vmware
  ci/infra/vmware/lb-instance.tf
  ci/infra/vmware/master-instance.tf
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/infra/vmware/variables.tf
  ci/infra/vmware/worker-instance.tf
Labels: backport, do not merge

#1249 Skuba auth login oidc ca
  cmd/skuba/auth/login.go
  docs/man/skuba-auth-login.1.md
  pkg/skuba/actions/auth/auth.go
  pkg/skuba/actions/auth/login.go
  pkg/skuba/actions/auth/login_test.go
  pkg/skuba/actions/auth/testdata/kube-apiserver.crt
  pkg/skuba/actions/auth/testdata/oidc-dex.crt
  pkg/skuba/actions/auth/testdata/oidc-dex.key
  pkg/skuba/actions/auth/testing.go
Labels: bug, enhancement

#1257 Revert kubelet server tls bootstrap (backport to v5)
  internal/pkg/skuba/deployments/ssh/kubelet.go
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubeadm/configmap_test.go
  internal/pkg/skuba/kubernetes/kubelet.go
  internal/pkg/skuba/kubernetes/versions.go
  pkg/skuba/actions/cluster/init/init.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: backport

#1251 cri: handle the migration to the new configuration format
  cmd/skuba/cluster/upgrade.go
  internal/pkg/skuba/deployments/ssh/cri.go
  internal/pkg/skuba/upgrade/cluster/cri.go
  internal/pkg/skuba/upgrade/cluster/cri_test.go
  internal/pkg/skuba/upgrade/cluster/testdata/addons/cri/default_flags
  pkg/skuba/actions/cluster/init/constants.go
  pkg/skuba/actions/cluster/init/init.go
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: 5.0.0, enhancement, v5

#1259 Ensure services are enabled
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: 5.0.0, backport

#1270 Ensure services are enabled
  ci/infra/aws/README.md
  ci/infra/aws/aws.tf
  ci/infra/aws/network.tf
  ci/infra/aws/terraform.tfvars.example
  ci/infra/aws/variables.tf
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/testrunner/platforms/libvirt.py
  ci/infra/testrunner/platforms/terraform.py
  ci/infra/testrunner/utils/config.py
  ci/infra/testrunner/vars.yaml
  ci/infra/vmware/terraform.tfvars.json.ci.example
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
  ci/jenkins/pipelines/skuba-e2e-test.Jenkinsfile
  ci/jenkins/templates/e2e-dev-template.yaml
  cmd/skuba/addon.go
  cmd/skuba/addon/refresh.go
  docs/man/skuba-addon-refresh-localconfig.1.md
  docs/man/skuba-node-bootstrap.1.md
  docs/man/skuba-node-join.1.md
  docs/man/skuba-node-upgrade-apply.1.md
  docs/man/skuba.1.md
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/addons_test.go
  internal/pkg/skuba/addons/cilium_test.go
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/deployments/ssh/ssh.go
  internal/pkg/skuba/kubeadm/configmap.go
  internal/pkg/skuba/kubeadm/configmap_test.go
  internal/pkg/skuba/upgrade/addon/versions_test.go
  internal/pkg/skuba/upgrade/node/versions_test.go
  pkg/skuba/actions/addon/refresh/localconfig.go
  pkg/skuba/actions/node/upgrade/apply.go
  skuba-update/skuba_update/skuba_update.py
Labels: 5.0.0, backport

#1267 [backport] cri: handle the migration to the new configuration format
  cmd/skuba/cluster/upgrade.go
  internal/pkg/skuba/deployments/ssh/cri.go
  internal/pkg/skuba/upgrade/cluster/cri.go
  internal/pkg/skuba/upgrade/cluster/cri_test.go
  internal/pkg/skuba/upgrade/cluster/testdata/addons/cri/default_flags
  pkg/skuba/actions/cluster/init/constants.go
  pkg/skuba/actions/cluster/init/init.go
  pkg/skuba/actions/cluster/upgrade/plan.go
  pkg/skuba/actions/node/upgrade/apply.go
Labels: 5.0.0, backport

#1210 Patternless cosmetic cleanups
  internal/pkg/skuba/deployments/ssh/kubernetes.go
  internal/pkg/skuba/deployments/ssh/zypper.go
  pkg/skuba/constants.go
Labels: 5.0.0, enhancement

#1269 Update Kubernetes to 1.18.6
  ci/infra/testrunner/tests/utils.py
  go.mod
  go.sum
  internal/pkg/skuba/kubernetes/versions.go
  internal/pkg/skuba/kubernetes/versions_test.go
Labels: ci-repo:k8s_cve_upgrade

#1265 Upgrade to k8s from 1.17.4 to 1.17.9
  ci/infra/testrunner/tests/utils.py
  ci/jenkins/jobs.yaml
  internal/pkg/skuba/kubernetes/versions.go
  pkg/skuba/actions/node/remove/remove_test.go
Labels: 5.0.0, backport, do not merge, v5

#1247 Enhance skuba addon upgrade [plan|apply]
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/tests/test_addon_upgrade.py
  internal/pkg/skuba/addons/addons.go
  internal/pkg/skuba/addons/addons_test.go
  pkg/skuba/actions/addon/upgrade/apply.go
  pkg/skuba/actions/addon/upgrade/plan.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
Labels: enhancement, v5

#1275 Fix name of kubernetes client package
  ci/Makefile
Labels: ci-worker:experimental, do not merge

#1276 Update node repositories to official SP2 repos
  ci/infra/libvirt/terraform.tfvars.json.ci.example
  ci/infra/openstack/terraform.tfvars.json.ci.example
  ci/infra/vmware/terraform.tfvars.json.ci.example
Labels: CI, ci-platform:openstack
