Repository SUSE/skuba, pull requests merged in 2020-01, with the labels that each got.

#901 Clean up testrunner parameters
  ci/infra/testrunner/README.md
  ci/infra/testrunner/platforms/platform.py
  ci/infra/testrunner/platforms/terraform.py
  ci/infra/testrunner/skuba/skuba.py
  ci/infra/testrunner/utils/constants.py
  ci/infra/testrunner/utils/utils.py
  ci/infra/testrunner/vars.yaml
Labels: ci

#909 add missing quotes
  ci/jenkins/pipelines/prs/skuba-code-lint.Jenkinsfile
Labels: ci, cosmetic, wip

#912 libvirt: Fix ip in testrunner
  ci/infra/testrunner/platforms/libvirt.py
Labels: bug, ci, do not merge

#894 Annotate CaaSP version on node
  README.md
  internal/pkg/skuba/deployments/ssh/skuba-update.go
  internal/pkg/skuba/deployments/ssh/systemd.go
  pkg/skuba/actions/cluster/status/status.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
  pkg/skuba/actions/node/upgrade/apply.go
  skuba-update/dev-requirements.txt
  skuba-update/skuba_update/skuba_update.py
  skuba-update/test/os/suse/Dockerfile.builder
  skuba-update/test/unit/skuba_update_test.py
Labels: bug

#927 Disable firewalld
  ci/infra/libvirt/cloud-init/lb.tpl
  ci/infra/vmware/cloud-init/common.tpl
  ci/infra/vmware/cloud-init/lb.tpl
  internal/pkg/skuba/deployments/ssh/firewalld.go
  pkg/skuba/actions/node/bootstrap/bootstrap.go
  pkg/skuba/actions/node/join/join.go
Labels: bug

#936 Added ablilty to set env var for pip verbosity
  ci/infra/testrunner/testrunner
  ci/jenkins/pipelines/prs/skuba-test-vmware.Jenkinsfile
  ci/jenkins/pipelines/prs/skuba-test.Jenkinsfile
Labels: ci

#937 Simplify jjb templates for nightly jobs
  ci/jenkins/jobs.yaml
  ci/jenkins/templates/e2e-nightly-template.yaml
Labels: ci

#916 Fix tf output
  ci/infra/aws/README.md
  ci/infra/aws/output.tf
  ci/infra/openstack/output.tf
  ci/infra/testrunner/platforms/libvirt.py
  ci/infra/testrunner/platforms/terraform.py
  ci/infra/testrunner/platforms/vmware.py
  ci/infra/vmware/output.tf
Labels: ci
